# Documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: []

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "monthly"
    labels: []

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: []
