# Documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: []
