name: Markdown Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
  # Run on first day of every month
  # See:
  #   - https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
  - cron: '0 0 1 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # https://github.com/marketplace/actions/markdown-link-check
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
