name: Markdown Checker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
  # Run on first day of every month
  # See:
  #   - https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
  - cron: '0 0 1 * *'

jobs:
  job-1:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v1

      # https://github.com/marketplace/actions/markdown-link-check
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
